<a href="https://colab.research.google.com/github/deepak1195/DeepLearning/blob/main/001_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%config Completer.use_jedi = False
%autosave 20

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

import plotly.express as px
import plotly.graph_objects as go

Autosaving every 20 seconds


In [ ]:
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
len(x_train)

60000

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [ ]:
x_train[0].shape

(28, 28)

In [ ]:
px.imshow(x_train[0])

In [ ]:
y_train[0]

5

In [ ]:
x_train=x_train/255
x_test=x_test/255

In [ ]:
x_train_flat=x_train.reshape(len(x_train),28*28)
x_test_flat=x_test.reshape(len(x_test),28*28)

In [ ]:
model=keras.Sequential([
        keras.layers.Dense(10, input_shape=(784,), activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_flat,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 2ms/step - loss: 0.4680 - accuracy: 0.8774
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3044 - accuracy: 0.9149
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2838 - accuracy: 0.9200
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2731 - accuracy: 0.9238
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2666 - accuracy: 0.9248


In [ ]:
model.evaluate(x_test_flat,y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.2751 - accuracy: 0.9226


[0.27513450384140015, 0.9225999712944031]

In [ ]:
y_pred=model.predict(x_test_flat)
y_pred

313/313 [==============================] - 0s 1ms/step


array([[2.94814613e-02, 3.88117940e-07, 5.09769581e-02, ...,
        9.99881208e-01, 7.98263475e-02, 6.01737440e-01],
       [4.52571332e-01, 8.40324536e-03, 9.99192357e-01, ...,
        1.16981392e-12, 9.48346406e-02, 1.69850445e-09],
       [3.25219356e-04, 9.89784420e-01, 5.44366360e-01, ...,
        1.31591037e-01, 2.36446142e-01, 3.55843343e-02],
       ...,
       [3.54699205e-06, 2.90868797e-06, 8.89723073e-04, ...,
        4.15197998e-01, 3.75926614e-01, 6.82738841e-01],
       [1.22847589e-04, 8.97240752e-05, 1.06888685e-04, ...,
        4.18974778e-05, 4.42565382e-01, 7.34696223e-05],
       [6.43869443e-03, 6.03426198e-10, 1.63243026e-01, ...,
        3.27069678e-08, 1.21292614e-04, 6.46818364e-07]], dtype=float32)

In [ ]:
px.imshow(x_test[12])

In [ ]:
y_pred[12]

array([1.2237402e-03, 6.1560513e-06, 2.9800681e-03, 6.8168722e-02,
       7.6801342e-01, 1.0533014e-01, 8.3598512e-04, 8.4512728e-01,
       1.8978474e-01, 9.8575431e-01], dtype=float32)

In [ ]:
np.argmax(y_pred[12])

9

In [ ]:
conMat=tf.math.confusion_matrix(labels=y_test,predictions=[np.argmax(i) for i in y_pred])
conMat

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 958,    0,    1,    1,    0,    6,    9,    4,    1,    0],
       [   0, 1119,    2,    2,    0,    1,    4,    2,    5,    0],
       [   3,   10,  927,   13,   14,    8,   13,   13,   27,    4],
       [   4,    0,   17,  902,    0,   48,    3,   16,   12,    8],
       [   1,    1,    3,    1,  933,    0,   11,    4,    7,   21],
       [   7,    2,    3,   17,   10,  811,   16,    4,   18,    4],
       [   7,    3,    6,    1,    8,   12,  918,    2,    1,    0],
       [   1,    6,   22,    4,    8,    1,    0,  965,    1,   20],
       [   8,   11,    7,   23,   10,   61,   11,   17,  820,    6],
       [   9,    7,    2,    9,   50,   14,    0,   42,    3,  873]],
      dtype=int32)>

In [ ]:
px.imshow(
    conMat,
    labels=dict(x="Predicted", y="Truth"),
    text_auto=True
)

In [ ]:
hlModel=keras.Sequential([
        keras.layers.Dense(100, input_shape=(784,), activation='relu'),
        keras.layers.Dense(10, activation='sigmoid')
])

hlModel.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

hlModel.fit(x_train_flat,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2743 - accuracy: 0.9207
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1263 - accuracy: 0.9629
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0877 - accuracy: 0.9736
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0669 - accuracy: 0.9791
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0518 - accuracy: 0.9840


In [ ]:
hlModel.evaluate(x_test_flat,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0842 - accuracy: 0.9746


[0.08422473073005676, 0.9746000170707703]

In [ ]:
hlY_pred=hlModel.predict(x_test_flat)

313/313 [==============================] - 1s 2ms/step


In [ ]:
mlConMat=tf.math.confusion_matrix(labels=y_test,predictions=[np.argmax(i) for i in hlY_pred])
mlConMat

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 968,    0,    1,    2,    3,    0,    2,    1,    0,    3],
       [   0, 1127,    4,    0,    0,    1,    1,    0,    2,    0],
       [   5,    1, 1006,    6,    2,    0,    2,    7,    3,    0],
       [   0,    3,    4,  988,    0,    3,    0,    5,    2,    5],
       [   1,    1,    3,    1,  945,    0,    4,    6,    0,   21],
       [   3,    1,    1,   13,    1,  864,    6,    0,    1,    2],
       [   4,    3,    2,    1,    3,    3,  940,    2,    0,    0],
       [   1,    6,   11,    1,    0,    0,    0, 1004,    1,    4],
       [   4,    2,    7,   10,    3,    5,    4,   10,  920,    9],
       [   2,    6,    0,    4,    2,    3,    1,    7,    0,  984]],
      dtype=int32)>

In [ ]:
px.imshow(
    mlConMat,
    labels=dict(x="Predicted", y="Truth"),
    text_auto=True
)

In [ ]:
hlModel1=keras.Sequential([
        keras.layers.Flatten(input_shape=(28,28)),
        keras.layers.Dense(120, activation='relu'),
        keras.layers.Dense(40, activation='relu'),
        keras.layers.Dense(10, activation='sigmoid')
])

hlModel1.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

hlModel1.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2542 - accuracy: 0.9266
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1078 - accuracy: 0.9680
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0755 - accuracy: 0.9767
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0577 - accuracy: 0.9820
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0445 - accuracy: 0.9856
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0361 - accuracy: 0.9880
Epoch 7/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0312 - accuracy: 0.9897
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0251 - accuracy: 0.9919
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0209 - accuracy: 0.9927
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.019