<a href="https://colab.research.google.com/github/deepak1195/DeepLearning/blob/main/004_BasicMatrixOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### Creating nxm Matrix

In [ ]:
revInDollars=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revInDollars

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

### Multiplying Scalar value with Matrix

In [ ]:
revInDollars*75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [ ]:
unitSold=np.array([[50,60,25],[10,13,5],[40,70,52]])
unitSold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [ ]:
ppu=np.array([20,30,15])
ppu

array([20, 30, 15])

### Multiplying nx1 Matrix with nxn Matrix

In [ ]:
unitSold*ppu

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])

### Dot Product

In [ ]:
np.dot(unitSold,ppu)

array([3175,  665, 3680])